[workspace]
members = ["crates/opeo", "crates/opeo-macros"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"
description = "Out-parameter error handling for Rust with typed failure proofs"
authors = ["shaogme <shaogme@gmail.com>"]
repository = "https://github.com/shaogme/opeo"
homepage = "https://github.com/shaogme/opeo"
documentation = "https://docs.rs/opeo"
keywords = ["error-handling", "out-parameters"]

[workspace.dependencies]
opeo-macros = { path = "crates/opeo-macros", version = "0.1.3" }

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "warn"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
panic_in_result_fn = "warn"
indexing_slicing = "warn"

